services:
  backend:
    container_name: "phpapch_service"
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      # - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      # - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/
    depends_on:
      - database
    networks:
      - network_default

  database:
    image: mysql:8.0
    container_name: "mysql_service"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - network_default

networks:
  network_default:

volumes:
  db_volume:
