services:
  backend:
    container_name: "phpapch_service"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database
    networks:
      - network_default
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  database:
    image: mysql:8.0
    container_name: "mysql_service"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql
      - ./docker/mysql/init-sql:/docker-entrypoint-initdb.d
    networks:
      - network_default

networks:
  network_default:

volumes:
  db_volume:
